spring.application.name=melodi
server.port=8080

# update.
# Multipart (img uploads)
spring.servlet.multipart.max-file-size=12MB
spring.servlet.multipart.max-request-size=14MB
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/melodi
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.show-sql=true
jwt-secret="C6UlILsE6GJwNqwCTkkvJj9O653yJUoteWMLfYyrc3vaGrrTOrJFAUD1wEBnnposzcQl"
jwt-expiration-ms=86400000

# ======================
# Gmail SMTP
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohammedhabib197@gmail.com
spring.mail.password=appPasswordShouldBeHere
spring.mail.protocol=smtp
#spring.mail.properties.mail.debug=true
#logging.level.org.springframework.mail=DEBUG
#logging.level.com.sun.mail=DEBUG
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.mail.from=mohammedhabib197@gmail.com
